# ruff.toml or pyproject.toml
[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "Q", "B", "I"]
ignore = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"